//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDTeamBuilderDatabaseGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public int Id { get; set; }
        public string Name_Of_Class { get; set; }
        public Nullable<int> Resolve_Level { get; set; }
        public Nullable<int> Max_HP { get; set; }
        public Nullable<decimal> Dodge_Percentage { get; set; }
        public Nullable<int> Protect { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> Accuracy_Modifier { get; set; }
        public Nullable<decimal> Critical_Chance_Percentage { get; set; }
        public Nullable<int> Damage_Minimum { get; set; }
        public Nullable<int> Damage_Maximum { get; set; }
        public Nullable<int> Stun_Resistance { get; set; }
        public Nullable<int> Move_Resistance { get; set; }
        public Nullable<int> Blight_Resistance { get; set; }
        public Nullable<int> Bleed_Resistance { get; set; }
        public Nullable<int> Debuff_Resistance { get; set; }
        public Nullable<int> Trap_Disarm_Chance { get; set; }
        public Nullable<int> Disease_Resistance { get; set; }
        public Nullable<int> Deathblow_Resistance { get; set; }
        public Nullable<int> Movement_Forward { get; set; }
        public Nullable<int> Movement_Backwards { get; set; }
        public string Religious { get; set; }
        public string Provisions { get; set; }
    }
}
